#!/bin/bash

echo "Running custom docker commands"

docker rm $(docker ps -aq)

docker volume rm project_keyshare

docker volume rm project_blocks

docker build -f med_python/Dockerfile -t harsh/med:v3 .

echo "Done Shit!"
