# version: '3.6'
#
# services:
#
#   settings-tp:
#     image: hyperledger/sawtooth-settings-tp:nightly
#     container_name: sawtooth-settings-tp
#     depends_on:
#       - validator
#     command: |
#       bash -c "
#         settings-tp -vv -C tcp://validator:4004
#       "
#     stop_signal: SIGKILL
#
#   intkey-tp-python:
#     build:
#       context: .
#       dockerfile: examples/intkey_python/Dockerfile
#       args:
#         - http_proxy
#         - https_proxy
#         - no_proxy
#     image: intkey-tp-python-local:${ISOLATION_ID}
#     volumes:
#       - ./:/project/sawtooth-sdk-python
#     container_name: intkey-tp-python-local
#     depends_on:
#       - validator
#     command: |
#       bash -c "
#         bin/protogen
#         cd examples/intkey_python
#         python3 setup.py clean --all
#         python3 setup.py build
#         intkey-tp-python -vv -C tcp://validator:4004
#       "
#     stop_signal: SIGKILL
#
#
#   xo-tp-python:
#     build:
#       context: .
#       dockerfile: examples/xo_python/Dockerfile
#       args:
#         - http_proxy
#         - https_proxy
#         - no_proxy
#     image: xo-tp-python-local:${ISOLATION_ID}
#     volumes:
#       - ./:/project/sawtooth-sdk-python
#     container_name: xo-tp-python-local
#     depends_on:
#       - validator
#     command: |
#       bash -c "
#         bin/protogen
#         cd examples/xo_python
#         python3 setup.py clean --all
#         python3 setup.py build
#         xo-tp-python -vv -C tcp://validator:4004
#       "
#     stop_signal: SIGKILL
#
#
#   client:
#     image: hyperledger/sawtooth-shell:nightly
#     container_name: sawtooth-shell
#     depends_on:
#       - validator
#     command: |
#       bash -c "
#         sawtooth keygen &&
#         tail -f /dev/null
#       "
#     stop_signal: SIGKILL
#
#
#   validator:
#     image: hyperledger/sawtooth-validator:nightly
#     container_name: sawtooth-validator
#     expose:
#       - 4004
#       - 8800
#       - 5050
#     ports:
#       - "4004:4004"
#     # start the validator with an empty genesis batch
#     command: |
#       bash -c "
#         sawadm keygen
#         sawset genesis \
#           -k /etc/sawtooth/keys/validator.priv \
#           -o config-genesis.batch && \
#         sawset proposal create \
#           -k /etc/sawtooth/keys/validator.priv \
#           sawtooth.consensus.algorithm.name=Devmode \
#           sawtooth.consensus.algorithm.version=0.1 \
#           -o config.batch && \
#         sawadm genesis config-genesis.batch config.batch && \
#         sawtooth-validator -vv \
#             --endpoint tcp://validator:8800 \
#             --bind component:tcp://eth0:4004 \
#             --bind network:tcp://eth0:8800 \
#             --bind consensus:tcp://eth0:5050 \
#       "
#     stop_signal: SIGKILL
#
#
#   rest-api:
#     image: hyperledger/sawtooth-rest-api:nightly
#     container_name: sawtooth-rest-api
#     ports:
#       - "8008:8008"
#     depends_on:
#       - validator
#     command: |
#       bash -c "
#         sawtooth-rest-api -v --connect tcp://validator:4004 --bind rest-api:8008
#       "
#     stop_signal: SIGKILL
#
#
#   devmode-rust:
#     image: hyperledger/sawtooth-devmode-engine-rust:nightly
#     container_name: sawtooth-devmode-engine-rust
#     depends_on:
#       - validator
#     command: |
#       bash -c "
#         devmode-engine-rust -v --connect tcp://validator:5050
#       "
#     stop_signal: SIGKILL
version: "2.1"

services:

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  med-tp-python:
    image: /home/harsh/project/med_python/dockerfile
    container_name: sawtooth-med-tp-python
    depends_on:
      - validator
    command: |
      bash -c "
        med-tp-python -vv -C tcp://validator:4004
      "
    stop_signal: SIGKILL

  validator:
    image: hyperledger/sawtooth-validator:1.1
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:1.1
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-default
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  shell:
    image: hyperledger/sawtooth-all:1.1
    container_name: sawtooth-shell-default
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""
